Catch Me If U Can: main.cpp File Reference
main.cpp File Reference
Main core of "catch me if you can" game.
#include <iostream>
#include <vector>
#include <random>
#include <iomanip>
#include <ncurses.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <fstream>
#include <utility>
Classes
struct SBonus
Defines a bonus.
struct SObstacle
Defines an obstacle.
struct SPlayer
Defines a player The SPlayer structure allows the creation of a player with the parameters : size (m_sizeX, m_sizeY), position (m_X, m_Y), and also a token (m_token), a score (m_score) and a movement history (m_history)
Typedefs
typedef vector< vector< char > > CMatrice
Alias to the matrix.
Functions
string AskForMap ()
Ask the player for map name.
bool CheckIfWin (SPlayer &PlayerX, SPlayer &PlayerY)
Check if someone won.
void ClearScreen ()
Clear console.
void Color (const string &Coul, const string &Hightlight="")
Print color.
void DetectObstacle (CMatrice &Map)
Detect obstacle for public map.
void DisplayEditor ()
Display game's map editor.
void DisplayHistory ()
void DisplayInfos (const SPlayer &Player)
Display infos about a specific player.
void DisplayLog ()
Display game's logs.
void DisplayMenu ()
Display game's meny.
void DisplayMulti ()
Display multiplayer game.
void DisplayOption ()
Display game's options.
void DisplaySoloIA ()
Display game agaisn't bot (IA)
void DisplayWin (const unsigned &Tour, const bool &IsBot=true)
Display win screen.
void ExportMatrice (CMatrice &Matrice, const string &DestFile)
Export matrix into a specific file.
void GenerateRandomObstacles (CMatrice &Matrice, const SObstacle &Obstacle, const unsigned &Totalsize)
Generate random obstacles into matrix.
void GenerateStaticObject (CMatrice &Map, unsigned &Difficulty, const unsigned &NbObs=0, const unsigned &NbBonus=0)
Generate random objects into map.
void GetBonus (CMatrice &Matrice, SPlayer &Player)
Check if player get bonus.
unsigned GetMaxColumn (const string &File)
Get the total of columns of a specific text file.
unsigned GetMaxLine (const string &File)
Get the total of lines of a specific text file.
unsigned GetTourMax ()
Ask player maximum round.
SPlayer GetWinner (const SPlayer &PlayerX, const SPlayer &PlayerY, const unsigned &NbrTour)
Get the game winner.
SBonus InitBonus (const unsigned AxeX, const unsigned AxeY, const char Token)
Initiate values to an empty bonus.
void InitCurses ()
Initiate curses allowing (with ListenKeyboard()) to detect key.
CMatrice InitMatrice (unsigned NbLine, unsigned NbColumn, SPlayer &PlayerX, SPlayer &PlayerY, bool ShowBorder=true)
Initiate values to an empty matrix.
SObstacle InitObstacle (const unsigned AxeX, const unsigned AxeY, const char Token)
Initiate values to an empty obstacle.
void InitOptions ()
Initiate defaults options.
SPlayer InitPlayer (const unsigned Largeur, const unsigned Hauteur, const unsigned AxeX, const unsigned AxeY, const char Token)
Initiate values to an empty player.
bool IsBonusTaken (const SPlayer &Player)
Check if player got the bonus that make his size up.
bool IsMovementForbidden (SPlayer &Player, char &Movement)
Check if player can move to the position he decided to go.
bool IsPersoMapRecquiered ()
Ask the player if a public map is wanted.
bool IsSurrounded (CMatrice &Map, SPlayer &Player)
Check if player is surrounded of obstacles.
const string KBleu ("34")
const string KBold ("1")
const string KCyan ("36")
void KeyEvent (const int &ch, CMatrice &Map, SPlayer &Player)
Move player to the position depending of what he typed.
const string KHBleu ("44")
const string KHCyan ("46")
const string KHGris ("47")
const string KHJaune ("43")
const string KHMagenta ("45")
const string KHNoir ("40")
const string KHRouge ("41")
const string KHVert ("42")
const string KJaune ("33")
const string KMagenta ("35")
const string KNoir ("30")
const string KOverLine ("53")
const string KReset ("0")
const string KRouge ("31")
const string KUnderLine ("4")
const string KVert ("32")
void ListenKeyboard ()
Listen to keyboard using no-canonical mode.
CMatrice LoadMapByFile (const string &MapName)
Load map by file.
int main ()
void MoveBot (int &ch, CMatrice &Map, const unsigned &Tour)
Move bot to a specific position.
void MovePlayer (CMatrice &Matrice, char Move, SPlayer &Player)
Move player to a specific position.
void PrintLines (const unsigned &LineNumber)
PrintLines.
void PutBonus (CMatrice &Matrice, SBonus &Bonus)
Put bonus to matrix.
void PutObstacle (CMatrice &Matrice, SObstacle &Obstacle)
Put obstacle to matrix.
int Rand (int Min, int Max)
Generate random number.
void SetConfig (string Name, const string &Value)
Modify a specific config.
void SetTextMiddle ()
Set text to the middle screen.
void ShowMatrice (const CMatrice &Matrice, const bool Clear=true)
Show matrix on console.
void ShowTitle (const string &FileName, const bool Clear=true)
Show title from file.
bool StrToBool (const string &Chaine)
Convert string to bool.
Variables
char BonusX
Bonus X token.
char BonusY
Bonus Y token.
char BonusZ
Bonus Z token.
bool BShowHistory
Showing history or not.
bool BShowRules
Showing rules or not.
char CaseBorder
Border case token.
char CaseEmpty
Empty case token.
char CaseObstacle
Obstacle case token.
char CMouvBot
Key associed to bot movement.
char CMouvLeft
Key associed to left movement.
char CMouvRight
Key associed to rigght movement.
char CMouvTop
Key associed to top movement.
unsigned KDifficult
Difficulty.
unsigned KSizeX
Matrix size (X axe)
unsigned KSizeY
Matrix size (Y axe)
SPlayer PlayerX
First player.
SPlayer PlayerY
First player.
struct winsize size
string SLog
log string
char TokenPlayerX
First player token.
char TokenPlayerY
Second player token.
vector< SObstacle > VObstacle
all referenced obstacles
vector< string > VOptionsName
options names
vector< string > VOptionValue
options values
Detailed Description
Main core of "catch me if you can" game.
Date
January 17 2017
Author
Kevin VALERIO, Mikael SALASCA, SOUTIF Thomas, TRAN Billy, ROUX Paul
Version
1.8
Definition in file main.cpp.
Typedef Documentation
typedef vector<vector <char> > CMatrice
Alias to the matrix.
Definition at line 33 of file main.cpp.
Function Documentation
string AskForMap ()
Ask the player for map name.
Returns
Output path
Definition at line 1107 of file main.cpp.
References Color(), and KReset().
Referenced by DisplayMulti(), and DisplaySoloIA().
                    {
     string MapName;
     cout << "\n\r[?] Quel est le nom de votre carte (Nom : mot comprit entre 'Mymap_' et '.map')? : ";
     Color(KReset);
     cin >> MapName;
     return MapName;
 } //AskForMap()
bool CheckIfWin (SPlayer & PlayerX, SPlayer & PlayerY)
Check if someone won.
Parameters
[in] PlayerX The first player
[in] PlayerY The second player
Returns
If PlayerX or PlayerY won
Definition at line 545 of file main.cpp.
References SPlayer::m_sizeX, SPlayer::m_sizeY, SPlayer::m_X, and SPlayer::m_Y.
Referenced by DisplayMulti(), and DisplaySoloIA().
{
     return !((PlayerX.m_X > PlayerY.m_X + PlayerY.m_sizeX - 1) ||
         (PlayerX.m_X + PlayerX.m_sizeX - 1 < PlayerY.m_X) ||
         (PlayerY.m_Y > PlayerX.m_Y + PlayerX.m_sizeY - 1) ||
         (PlayerY.m_Y + PlayerY.m_sizeY - 1 < PlayerX.m_Y));
 } //CheckIfWin()
void ClearScreen ()
Clear console.
Definition at line 222 of file main.cpp.
Referenced by DisplayEditor(), DisplayMenu(), DisplayMulti(), DisplayOption(), DisplaySoloIA(), DisplayWin(), ShowMatrice(), and ShowTitle().
                    {
     cout << "\033[H\033[2J";
 }//ClearScreen()
void Color (const string & Coul, const string & Hightlight = "")
Print color.
Parameters
[in] Coul Color wanted
[in] Hightlight Optional highlight wanted
Definition at line 175 of file main.cpp.
Referenced by AskForMap(), DisplayEditor(), DisplayInfos(), DisplayLog(), DisplayMenu(), DisplayMulti(), DisplayOption(), DisplaySoloIA(), DisplayWin(), GetTourMax(), IsPersoMapRecquiered(), main(), and ShowMatrice().
{
     if (Hightlight != "")
         cout << "\033[34m\033[" << Hightlight << "m";
     else
         cout << "\033[" << Coul << "m";
 } //Color()
void DetectObstacle (CMatrice & Map)
Detect obstacle for public map.
Parameters
[in] Map Game's map
Definition at line 1158 of file main.cpp.
References CaseObstacle, InitObstacle(), and VObstacle.
Referenced by DisplayMulti(), and DisplaySoloIA().
{
     SObstacle TmpObstacle;
     for (unsigned i(0); i < Map.size(); ++i) {
         for (unsigned a(0); a < Map[i].size(); ++a) {
             if (Map[i][a] == CaseObstacle) {
                 TmpObstacle = InitObstacle(i, a, 'e');
                 VObstacle.push_back(TmpObstacle);
             }
         }
     }
 } //DetectObstacle()
void DisplayEditor ()
Display game's map editor.
Bug:
L'editeur ne s'affiche pas sur toutes les consoles
Definition at line 1483 of file main.cpp.
References BonusX, BonusY, BonusZ, CaseEmpty, CaseObstacle, ClearScreen(), Color(), DisplayMenu(), ExportMatrice(), InitBonus(), InitCurses(), InitMatrice(), InitObstacle(), InitPlayer(), KBleu(), KCyan(), KHJaune(), KReset(), KRouge(), ListenKeyboard(), SPlayer::m_X, SPlayer::m_Y, MovePlayer(), PlayerX, PlayerY, PrintLines(), PutBonus(), PutObstacle(), ShowMatrice(), ShowTitle(), and SLog.
Referenced by DisplayMenu().
                      {
     int Key;
     bool IsFirstTime = true;
     unsigned NbLine, NbColumn;
     ShowTitle("editor.title");
     for (unsigned i(0); i < 3; ++i) cout << endl;
     Color(KCyan);
     cout << "Quelle sera la taille de la carte ? \n\rTaille en hauteur : ";
     cin >> NbLine;
     cout << "Taille en largeur : ";
     cin >> NbColumn;
     CMatrice EmptyMatrice = InitMatrice(NbLine, NbColumn, PlayerX, PlayerY);
     SPlayer EmptyPlayer = InitPlayer(1, 1, 1, 1, '-');
     SBonus EmptyBonus;
     SObstacle EmptyObstacle;
     InitCurses();
     while (true) {
         ShowTitle("editor.title");
         PrintLines(3);
         Color(KBleu, KHJaune);
         cout << "[+] Votre carte ressemble actuellement  cela : \n\r";
         ShowMatrice(EmptyMatrice, false);
         Color(KCyan);
         cout << "\n\r\r\n\rUtilisez les A,Z,S,D pour vous diriger sur la map. \n\rCliquez sur " << BonusX << ", " << BonusY << " ou " << BonusZ << " pour placer des bonus" <<
             "\n\rCliquez sur ENTREE pour placer des obstacles\n\rUne fois votre edition finie, veuillez cliquer sur la touche M (menu)\n\r\n\rPour sauvegarder, veuillez maintenir CTRL+S. \n\r";
         Color(KReset);
         ListenKeyboard();
         if (!IsFirstTime)
             Key = getch();
         refresh();
         endwin();
         if (Key == 'm') {
             DisplayMenu();
             endwin();
             break;
         }
         //DEPLACEMENTS
         else if (Key == 'z')
             MovePlayer(EmptyMatrice, Key, EmptyPlayer);
         else if (Key == 'q')
             MovePlayer(EmptyMatrice, Key, EmptyPlayer);
         else if (Key == 's')
             MovePlayer(EmptyMatrice, Key, EmptyPlayer);
         else if (Key == 'd')
             MovePlayer(EmptyMatrice, Key, EmptyPlayer);
         //CREATION BONUS
         else if (Key == tolower(BonusX)) {
             EmptyBonus = InitBonus(EmptyPlayer.m_X, EmptyPlayer.m_Y, BonusX);
             MovePlayer(EmptyMatrice, 'd', EmptyPlayer);
             PutBonus(EmptyMatrice, EmptyBonus);
         }
         else if (Key == tolower(BonusY)) {
             EmptyBonus = InitBonus(EmptyPlayer.m_X, EmptyPlayer.m_Y, BonusY);
             MovePlayer(EmptyMatrice, 'd', EmptyPlayer);
             PutBonus(EmptyMatrice, EmptyBonus);
         }
         else if (Key == tolower(BonusZ)) {
             EmptyBonus = InitBonus(EmptyPlayer.m_X, EmptyPlayer.m_Y, BonusZ);
             MovePlayer(EmptyMatrice, 'd', EmptyPlayer);
             PutBonus(EmptyMatrice, EmptyBonus);
         }
         //OBSTACLE
         else if ('\n' == Key /*ENTREE*/) {
             EmptyObstacle = InitObstacle(EmptyPlayer.m_X, EmptyPlayer.m_Y, CaseObstacle);
             MovePlayer(EmptyMatrice, 'd', EmptyPlayer);
             PutObstacle(EmptyMatrice, EmptyObstacle);
         }
         //SAVE
         else if ((char(19)) == Key /*CTRL+S*/) {
             EmptyMatrice[EmptyPlayer.m_Y][EmptyPlayer.m_X] = CaseEmpty;
             string Name;
             Color(KRouge);
             cout << "\n\r[?] Nom de la map ? ";
             cin >> Name;
             string FullName = "./map/MyMap_" + Name + ".map";
             ExportMatrice(EmptyMatrice, FullName);
             Color(KCyan);
             cout << "[+]Map exporte  l'emplacement : " << FullName << "\n\r";
             Color(KReset);
             refresh();
             endwin();
             SLog.clear();
             DisplayMenu();
         }
         ClearScreen();
         IsFirstTime = false;
         //SOLVING OBSTACLE BUG FOR MAP CREATION
         EmptyMatrice[1][1] = CaseEmpty;
     }
     ShowMatrice(EmptyMatrice);
     refresh();
     endwin();
     DisplayMenu();
 }//DisplayEditor()
void DisplayHistory ()
void DisplayInfos (const SPlayer & Player)
Display infos about a specific player.
Parameters
[in] Player Player's info
Definition at line 1268 of file main.cpp.
References BonusX, BonusY, BonusZ, BShowRules, CaseObstacle, Color(), DisplayLog(), KCyan(), KDifficult, KHVert(), KJaune(), KReset(), KRouge(), KSizeX, KSizeY, KVert(), and SPlayer::m_score.
Referenced by DisplayMulti(), and DisplaySoloIA().
{
     Color(KVert);
     cout << endl << "[+] Difficult : " << KDifficult << flush << endl << '\r';
     Color(KCyan);
     cout << endl << "[+] Taille : (" << KSizeX << ", " << KSizeY << ')' << endl << '\r';
     Color(KReset);
     if (BShowRules) {
         cout << endl << "[!] Regles :" << endl << '\r' << setw(5) << "Les bonus reprsents par des " << BonusX
             << ", " << BonusY << ", " << BonusZ << " ont diffrentes proprits."
             << endl << setw(5) << "\rA vous de les dcouvrir !" << endl << '\r'
             << "Enfin, les obstacles sont reprsents par des '" << CaseObstacle << "'." << endl << '\r'
             << "Les obstacles et les bonus sont gnrs de faon"; Color(KRouge); cout << " ALEATOIRE. "; Color(KReset); cout << endl << '\r' <<
             "Leur nombre dpend de la difficult choisie. Il se peut qu'aucun bonus n'aparaisse." << endl << '\r'
             << "Pour se dplacer, utilisez les touches Z, Q, S, D (en minuscule)." << endl << '\r';
     }
     Color(KJaune);
     cout << endl << "[!] Attention :" << endl << '\r' << "Si vous tes bloqus, veuillez appuyer sur la touche "; Color(KRouge, KHVert);
     cout << 'R'; Color(KReset); Color(KJaune);
     cout << " (restart)" << endl << '\r';
     Color(KCyan); cout << endl << "[+] Votre score est de : " << Player.m_score << endl << '\r'; Color(KReset);
     DisplayLog();
 }//DisplayInfos
void DisplayLog ()
Display game's logs.
Definition at line 1254 of file main.cpp.
References Color(), KHGris(), KReset(), KRouge(), and SLog.
Referenced by DisplayInfos(), and DisplayMenu().
                   {
     if (SLog != "") {
         Color(KRouge, KHGris);
         cout << endl << "[!] Dernire information : " << SLog << "\n\r";
         SLog.clear();
     }
     Color(KReset);
 } // DisplayLog()
void DisplayMenu ()
Display game's meny.
Definition at line 1341 of file main.cpp.
References ClearScreen(), Color(), DisplayEditor(), DisplayLog(), DisplayMulti(), DisplayOption(), DisplaySoloIA(), KCyan(), KHCyan(), KHJaune(), KReset(), KRouge(), and ShowTitle().
Referenced by DisplayEditor(), DisplayOption(), and main().
                    {
     unsigned Choice(0);
     ClearScreen();
     ShowTitle("menu.title");
     vector <string> menulist = { "Jouer contre l'ordinateur (IA)", "Jouer  plusieurs", "Editeur de map" ,"Options", "Quitter" };
     Color(KCyan, KHJaune); cout << "\n\r[!] Recommandation : agrandissez-la console !" << endl << endl << '\r'; Color(KReset);
     for (string option : menulist) {
         ++Choice;
         cout << ' ';
         Color(KRouge);
         cout << "[" << Choice << "] ";
         Color(KReset);
         cout << option << endl << endl;
     }
     DisplayLog();
     cout << endl << "[?] Choissisez entre [1-" << menulist.size() << "] : ";
     unsigned input;
     cin >> input;
     switch (input) {
     case 1:
         DisplaySoloIA();
         break;
     case 2:
         DisplayMulti();
         break;
     case 3:
         DisplayEditor();
         break;
     case 4:
         DisplayOption();
         break;
     case 5:
         exit(0);
     default:
         Color(KRouge, KHCyan);
         cout << endl << "[!] Choix invalide !" << endl;
         Color(KReset);
     }
 } //DisplayMenu()
void DisplayMulti ()
Display multiplayer game.
Definition at line 1180 of file main.cpp.
References AskForMap(), CheckIfWin(), ClearScreen(), Color(), DetectObstacle(), DisplayInfos(), DisplayWin(), GenerateStaticObject(), GetTourMax(), InitCurses(), InitMatrice(), InitPlayer(), IsPersoMapRecquiered(), KBleu(), KDifficult, KeyEvent(), KHJaune(), KMagenta(), KReset(), KSizeX, KSizeY, ListenKeyboard(), LoadMapByFile(), SPlayer::m_token, PlayerX, PlayerY, PrintLines(), Rand(), SetTextMiddle(), ShowMatrice(), ShowTitle(), TokenPlayerX, and TokenPlayerY.
Referenced by DisplayMenu().
                     {
     unsigned Nbround = GetTourMax();
     int ch;
     CMatrice Map;
     PlayerX = InitPlayer(1, 1, 1, 1, TokenPlayerX);
     if (IsPersoMapRecquiered()) {
         Map = LoadMapByFile(AskForMap());
         DetectObstacle(Map);
         PlayerY = InitPlayer(1, 1, KSizeX - 2, KSizeY - 2, TokenPlayerY);
     }
     else {
         Map = InitMatrice(KSizeX + 1, KSizeY + 1, PlayerX, PlayerY); /* +1 due  la bordure de '#' le long de la Matrice */
         if (KDifficult == 1)
             GenerateStaticObject(Map, KDifficult, 6, 5);
         else if (KDifficult == 2)
             GenerateStaticObject(Map, KDifficult, Rand(7, 9), 4);
         PlayerY = InitPlayer(1, 1, KSizeX - 1, KSizeY - 1, TokenPlayerY);
     }
     InitCurses();
     ShowMatrice(Map, false);
     for (unsigned i(0); i < Nbround * 2; ++i) {
         SPlayer &actualPlayer = (i % 2 == 0 ? PlayerX : PlayerY);
         ShowTitle("multi.title");
         ShowMatrice(Map, false);
         ListenKeyboard();
         DisplayInfos(actualPlayer);
         Color(KMagenta);
         cout << endl << "[?] Au Tour du joueur '"; Color(KBleu); cout << actualPlayer.m_token << '\'' << endl << '\r';
         Color(KReset);
         if (0 != i) ch = getch();
         KeyEvent(ch, Map, actualPlayer);
         if (CheckIfWin(PlayerX, PlayerY)) {
             DisplayWin(i);
             return;
         }
         refresh();
         endwin();
         Color(KBleu, KHJaune);
         ClearScreen();
         SetTextMiddle();
         PrintLines(16);
         cout << "[!] Egalit !" << endl;
         Color(KReset);
         endwin();
     }
 }//DisplayMulti()
void DisplayOption ()
Display game's options.
Bug:
Erreur lorsqu'on essaye d'entrer une valeur d'option diffrente de celles proposes
Definition at line 1302 of file main.cpp.
References ClearScreen(), Color(), DisplayMenu(), KCyan(), KReset(), KRouge(), SetConfig(), ShowTitle(), SLog, VOptionsName, and VOptionValue.
Referenced by DisplayMenu().
                      {
     ClearScreen();
     ShowTitle("option.title");
     cout << endl << endl << "Liste des options par defaut : " << endl << endl;
     for (unsigned i(0); i < VOptionsName.size(); ++i) cout << i << ". " << VOptionsName[i] << " : '" << VOptionValue[i] << '\'' << endl;
     Color(KRouge);
     cout << endl << "[!] Attention, ces configurations ne seront prsentes jusqu' la fermeture complte du jeu." << endl;
     unsigned Numero;
     string NewParam;
     Color(KCyan);
     cout << endl << "[+] Afin de modifier un paramtre, veuillez entrer le numro correspondant : ";
     cin >> Numero;
     if (Numero > VOptionsName.size()) {
         SLog += "Vous avez t renvoy au menu car le paramtre ne correspondait  aucune valeur.";
         DisplayMenu();
         return;
     }
     cout << VOptionsName[Numero] << " deviendra : ";
     cin >> NewParam;
     SetConfig(VOptionsName[Numero], NewParam);
     Color(KReset);
     DisplayMenu();
     Color(KReset);
 }//DisplayOption()
void DisplaySoloIA ()
Display game agaisn't bot (IA)
Definition at line 1397 of file main.cpp.
References AskForMap(), CheckIfWin(), ClearScreen(), Color(), DetectObstacle(), DisplayInfos(), DisplayWin(), GenerateStaticObject(), GetTourMax(), InitCurses(), InitMatrice(), InitPlayer(), IsPersoMapRecquiered(), KBleu(), KDifficult, KeyEvent(), KHJaune(), KMagenta(), KReset(), KSizeX, KSizeY, ListenKeyboard(), LoadMapByFile(), SPlayer::m_token, MoveBot(), PlayerX, PlayerY, PrintLines(), Rand(), SetTextMiddle(), ShowMatrice(), ShowTitle(), TokenPlayerX, and TokenPlayerY.
Referenced by DisplayMenu().
                      {
     unsigned Nbround = GetTourMax();
     bool IsPublicMap = IsPersoMapRecquiered();
     int Key;
     CMatrice Map;
     unsigned TourIA, Tour(0);
     PlayerX = InitPlayer(1, 1, 1, 1, TokenPlayerX);
     if (IsPublicMap) {
         PlayerY = InitPlayer(1, 1, KSizeX - 2, KSizeY - 2, TokenPlayerY);
         Map = LoadMapByFile(AskForMap());
         DetectObstacle(Map);
     }
     else {
         PlayerY = InitPlayer(1, 1, KSizeX - 1, KSizeY - 1, TokenPlayerY);
         Map = InitMatrice(KSizeX + 1, KSizeY + 1, PlayerX, PlayerY); /* +1 due  la bordure de '#' le long de la Matrice */
         if (KDifficult == 1)
             GenerateStaticObject(Map, KDifficult, 6, 5);
         else
             GenerateStaticObject(Map, KDifficult, Rand(7, 9), 4);
     }
     InitCurses();
     SetTextMiddle();
     ShowMatrice(Map);
     for (; Tour < Nbround * 2; ++Tour) {
         /*PlayerX = User. PlayerY = IA.*/
         SPlayer &actualPlayer = (Tour % 2 == 0 ? PlayerX : PlayerY);
         PrintLines(1);
         ShowTitle("solo.title");
         ShowMatrice(Map, false);
         ListenKeyboard();
         DisplayInfos(PlayerX);
         Color(KMagenta);
         cout << endl << "[+] A vous de jouer '"; Color(KBleu); cout << PlayerX.m_token << "' !" << endl << '\r';
         Color(KReset);
         if (!(Tour % 2 == 0))
             Key = getch();
         if (actualPlayer.m_token == PlayerX.m_token)
             KeyEvent(Key, Map, PlayerX);
         else if (actualPlayer.m_token == PlayerY.m_token) {
             MoveBot(Key, Map, TourIA);
             ++TourIA;
         }
         if (CheckIfWin(PlayerX, PlayerY)) {
             DisplayWin(Tour, false);
             return;
         }
         refresh();
         endwin();
         Color(KBleu, KHJaune);
         ClearScreen();
         SetTextMiddle();
         PrintLines(16);
         cout << "[!] Egalit !" << endl;
         Color(KReset);
         endwin();
     }
 } //DisplaySoloIA()
void DisplayWin (const unsigned & Tour, const bool & IsBot = true)
Display win screen.
Parameters
[in] The final round number
[in] IsBot (Optional) Is the game agains't IA
Definition at line 570 of file main.cpp.
References BShowHistory, ClearScreen(), Color(), GetWinner(), KHBleu(), KHCyan(), KHGris(), KHJaune(), KReset(), KRouge(), SPlayer::m_history, SPlayer::m_score, SPlayer::m_token, PlayerX, PlayerY, and PrintLines().
Referenced by DisplayMulti(), and DisplaySoloIA().
{
     SPlayer Winner = GetWinner(PlayerX, PlayerY, Tour);
     if (IsBot)
         ClearScreen();
     PrintLines(1);
     Color(KRouge, KHCyan);
     PrintLines(6);
     cout << endl << endl << "[!] Le joueur '" << Winner.m_token << "' a gagn avec : ";
     Color(KHBleu, KHGris); cout << Winner.m_score;
     Color(KRouge, KHCyan); cout << " points" << '!' << endl << '\r';
     if (BShowHistory) {
         PrintLines(3);
         Color(KRouge, KHJaune);
         cout << "Historique du gagnant : \n\r" << endl << "n | Mouv \n\r" << "________\n\r";
         for (unsigned i(0); i < Winner.m_history.size(); ++i)
             cout << "| " << i << " | " << Winner.m_history[i] << " | " << "\n\r";
     }
     Color(KReset);
     endwin();
     return;
 } //DisplayWin()
void ExportMatrice (CMatrice & Matrice, const string & DestFile)
Export matrix into a specific file.
Parameters
[in] Matrice Matrix to export
[in] DestFile The output file
Definition at line 1079 of file main.cpp.
Referenced by DisplayEditor().
{
     string StrMatrice;
     for (unsigned i(0); i < Matrice.size(); ++i) {
         for (unsigned a(0); a < Matrice[i].size(); ++a) {
             StrMatrice += Matrice[i][a];
         }
         if (i < Matrice.size() - 1)
             StrMatrice += '\n';
     }
     ofstream ofs(DestFile);
     if (ofs.is_open()) {
         ofs << StrMatrice;
         ofs.close();
     }
     else cout << "[!] Impossible d'crire ici...\n\r";
     cout << "[+] Fin de l'opration !";
 } //ExportMatrice()
void GenerateRandomObstacles (CMatrice & Matrice, const SObstacle & Obstacle, const unsigned & Totalsize)
Generate random obstacles into matrix.
Parameters
[in] Matrice Matrix where the obstacle will be put on
[in] Obstacle Obstacle to put
[in] Totalsize Number of obstacle to put
Definition at line 737 of file main.cpp.
References SObstacle::m_X, SObstacle::m_Y, PutObstacle(), and Rand().
Referenced by GenerateStaticObject().
{
     SObstacle NewObstacle = Obstacle;
     vector <unsigned> Randomvalues;
     for (unsigned i(0); i < Totalsize; ++i) Randomvalues.push_back(Rand(1, 2));
     for (unsigned i(0); i < Totalsize; ++i) {
         if (1 == Randomvalues[i]) {
             ++NewObstacle.m_Y;
             PutObstacle(Matrice, NewObstacle);
         }
         else if (2 == Randomvalues[i]) {
             ++NewObstacle.m_X;
             PutObstacle(Matrice, NewObstacle);
         }
     }
 } //GenerateRandomObstacles()
void GenerateStaticObject (CMatrice & Map, unsigned & Difficulty, const unsigned & NbObs = 0, const unsigned & NbBonus = 0)
Generate random objects into map.
Parameters
[in] Map Map where objects will be put on
[in] Difficulty The game difficulty
[in] NbObs Number of obstacle to print
[in] NbBonus Number of bonus to print
Definition at line 813 of file main.cpp.
References BonusX, BonusY, BonusZ, CaseObstacle, GenerateRandomObstacles(), InitBonus(), InitObstacle(), IsSurrounded(), KSizeX, KSizeY, SPlayer::m_X, SObstacle::m_X, SPlayer::m_Y, SObstacle::m_Y, PlayerX, PlayerY, PutBonus(), and Rand().
Referenced by DisplayMulti(), DisplaySoloIA(), and GetBonus().
{
     SObstacle TmpObs;
     SBonus TmpBonus;
     int RndBX, RndBY;
     unsigned Choix;
     if (1 == Difficulty) {/*EASY*/
         for (unsigned i(0); i < NbObs; ++i) {
             int MaxX = round((KSizeX / 2)) + Rand(1, 2);
             int MaxY = round((KSizeY / 2)) - Rand(0, 1);
             int RndX = round(Rand(2, MaxX));
             int RndY = round(Rand(2, MaxY));
             TmpObs = InitObstacle(RndX, RndY, CaseObstacle);
             if ((PlayerX.m_X == TmpObs.m_X && PlayerX.m_Y == TmpObs.m_Y)
                 && PlayerY.m_X == TmpObs.m_X && PlayerY.m_Y == TmpObs.m_Y) {
                 --i;
                 continue;
             }
             else {
                 if (!(IsSurrounded(Map, PlayerX)) || !(IsSurrounded(Map, PlayerY)))
                     GenerateRandomObstacles(Map, TmpObs, Rand(1, 3));
             }
         }
         for (unsigned i(0); i < NbBonus; ++i) {
             Choix = Rand(1, 3);
             RndBX = Rand(round(KSizeX - round(KSizeX / 3)) - Rand(1, 3), round(KSizeX - round(KSizeX / 5)) + Rand(1, 3));
             RndBY = Rand(round(KSizeY - round(KSizeY / 3)) - Rand(1, 3), round(KSizeY - round(KSizeY / 5)) + Rand(1, 3));
             if (Choix == 1) TmpBonus = InitBonus(RndBX - 1, RndBY, BonusY);
             else if (Choix == 2) TmpBonus = InitBonus(RndBX - 1, RndBY, BonusX);
             else if (Choix == 3) TmpBonus = InitBonus(RndBX - 1, RndBY, BonusZ);
             PutBonus(Map, TmpBonus);
         }
     }
     else if (2 == Difficulty) { /*HARD*/
         for (unsigned i(0); i < NbObs; ++i) {
             unsigned MinX = round((KSizeX / 2)) - Rand(1, 3);
             unsigned MaxX = round((KSizeX / 2)) + Rand(1, 2);
             unsigned MinY = round((KSizeY / 2)) - Rand(3, 4);
             unsigned MaxY = round((KSizeY / 2)) + Rand(2, 3);
             unsigned RndX = round(Rand(MinX, MaxX));
             unsigned RndY = round(Rand(MinY, MaxY));
             TmpObs = InitObstacle(RndX, RndY, CaseObstacle);
             if ((PlayerX.m_X == TmpObs.m_X && PlayerX.m_Y == TmpObs.m_Y)
                 && PlayerY.m_X == TmpObs.m_X && PlayerY.m_Y == TmpObs.m_Y) {
                 --i;
                 continue;
             }
             else {
                 if (!(IsSurrounded(Map, PlayerX)) || !(IsSurrounded(Map, PlayerY)))
                     GenerateRandomObstacles(Map, TmpObs, Rand(2, 5));
             }
         }
         RndBX = Rand(round(KSizeX - round(KSizeX / 3)) - Rand(1, 3), round(KSizeX - round(KSizeX / 5)));
         RndBY = Rand(round(KSizeY - round(KSizeY / 3)) - Rand(1, 3), round(KSizeY - round(KSizeY / 5)));
         for (unsigned i(0); i < NbBonus; ++i) {
             Choix = Rand(1, 3);
             if (1 == Choix)  TmpBonus = InitBonus(RndBX - 1, RndBY, BonusY);
             else if (2 == Choix) TmpBonus = InitBonus(RndBX - 1, RndBY, BonusX);
             else if (3 == Choix) TmpBonus = InitBonus(RndBX - 1, RndBY, BonusZ);
             PutBonus(Map, TmpBonus);
         }
     }
     else cout << '\r' << endl << "[!] Vrifiez vos options, le difficult doit tre comprise entre 1 (facile) et 2 (difficile)" << endl;
 }//GenerateStaticObject
void GetBonus (CMatrice & Matrice, SPlayer & Player)
Check if player get bonus.
Parameters
[in] Matrice The game map
[in] Player The player to check
Definition at line 639 of file main.cpp.
References BonusX, BonusY, BonusZ, GenerateStaticObject(), KDifficult, SPlayer::m_score, SPlayer::m_sizeX, SPlayer::m_sizeY, SPlayer::m_token, SPlayer::m_X, SPlayer::m_Y, and SLog.
Referenced by MovePlayer().
{
     for (unsigned i(Player.m_Y); i < Player.m_Y + Player.m_sizeY; ++i) {
         for (unsigned j(Player.m_X); j < Player.m_X + Player.m_sizeX; ++j) {
             //Dbut de la dtction des bonus
             if (Matrice[i][j] == BonusX) {
                 if (Player.m_X == 1) SLog += "\n\rVous avez dj prit un bonus de ce type !";
                 ++Player.m_sizeX;
                 ++Player.m_sizeY;
                 SLog += "\n\rVotre taille a augment!. \n\rVous pouvez dsorm traverser les obstacles";
                 Player.m_score += 25;
                 SLog += "\n\r\n\rCe bonus vous a fait gagner 25 points!";
             }
             if (Matrice[i][j] == BonusY) {
                 Player.m_score += 15;
                 SLog += "\n\r\n\rCe bonus ne fait strictement rien\n\rExcept vous faire gagner 15 points!";
             }
             if (Matrice[i][j] == BonusZ) {
                 SLog += "\n\rDes obstacles alatoires ont t placs!";
                 Player.m_score += 10;
                 SLog += "\n\r\n\rCe bonus vous a fait gagner 10 points!";
                 GenerateStaticObject(Matrice, KDifficult, 2, 1);
             }
             //Fin de la dtction des bonus
             for (unsigned i(Player.m_Y); i < Player.m_Y + Player.m_sizeY; ++i)
                 for (unsigned j(Player.m_X); j < Player.m_X + Player.m_sizeX; ++j)
                     Matrice[i][j] = Player.m_token;
         }
     }
 }//GetBonus()
unsigned GetMaxColumn (const string & File)
Get the total of columns of a specific text file.
Parameters
[in] File File to read in
Returns
Total of "File" columns
Definition at line 390 of file main.cpp.
Referenced by LoadMapByFile().
{
     string Line;
     ifstream ReadedMap(File);
     //Retourne la taille de la premire ligne du fichier
     getline(ReadedMap, Line);
     return Line.length();
 }//GetMaxColumn
unsigned GetMaxLine (const string & File)
Get the total of lines of a specific text file.
Parameters
[in] File File to read in
Returns
Total of "File" line
Definition at line 371 of file main.cpp.
Referenced by LoadMapByFile().
{
     string Line;
     unsigned NbLine(0);
     ifstream ReadedMap(File);
     while (!ReadedMap.eof()) {
         getline(ReadedMap, Line);
         ++NbLine;
     }
     return NbLine;
 }//GetMaxLine
unsigned GetTourMax ()
Ask player maximum round.
Returns
Return the maximum round
Bug:
Lorsque la valeur saisie est diffrente d'un entier naturel le programme tourne en boucle
Definition at line 190 of file main.cpp.
References Color(), KCyan(), KReset(), and KRouge().
Referenced by DisplayMulti(), and DisplaySoloIA().
                       {
     unsigned Nbround;
     Color(KCyan);
     cout << endl << "[?] Entrez le nombre de rounds : ";
     while (!(cin >> Nbround)) {
         Color(KRouge);
         cout << "\n\r[!] Le nombre de tour est incorrect. Veillez ressayer : \n\r";
         cin.clear();
         break;
     }
     Color(KReset);
     return Nbround;
 } //GetTourMax()
SPlayer GetWinner (const SPlayer & PlayerX, const SPlayer & PlayerY, const unsigned & NbrTour)
Get the game winner.
Parameters
[in] PlayerX The first player
[in] PlayerY The second player
[in] NbrTour The final round number
Returns
The game winner
Definition at line 560 of file main.cpp.
Referenced by DisplayWin().
{
     return (NbrTour % 2 == 0 ? PlayerX : PlayerY);
 } //GetWinner()
SBonus InitBonus (const unsigned AxeX, const unsigned AxeY, const char Token)
Initiate values to an empty bonus.
Parameters
[in] AxeX Position X of bonus
[in] AxeY Position Y of bonus
[in] Token Bonus token
Returns
Final bonus
Definition at line 613 of file main.cpp.
References SBonus::m_token, SBonus::m_X, and SBonus::m_Y.
Referenced by DisplayEditor(), and GenerateStaticObject().
{
     SBonus Bonus;
     Bonus.m_X = AxeX;
     Bonus.m_Y = AxeY;
     Bonus.m_token = Token;
     return Bonus;
 }//InitBonus()
void InitCurses ()
Initiate curses allowing (with ListenKeyboard()) to detect key.
Definition at line 251 of file main.cpp.
References size.
Referenced by DisplayEditor(), DisplayMulti(), and DisplaySoloIA().
                   {
     initscr();
     ioctl(STDOUT_FILENO, TIOCGWINSZ, &size);
 } //InitCurses()
CMatrice InitMatrice (unsigned NbLine, unsigned NbColumn, SPlayer & PlayerX, SPlayer & PlayerY, bool ShowBorder = true)
Initiate values to an empty matrix.
Parameters
[in] NbLine The matrix size (axe Y)
[in] NbColumn The matrix size (axe X)
[in] PlayerX The first player that will be put on the matrice
[in] PlayerY The second player that will be put on the matrice
[in] ShowBorder Creating borders or not
Returns
The completed matrix
Definition at line 409 of file main.cpp.
References CaseBorder, CaseEmpty, SPlayer::m_sizeX, SPlayer::m_sizeY, SPlayer::m_token, SPlayer::m_X, and SPlayer::m_Y.
Referenced by DisplayEditor(), DisplayMulti(), DisplaySoloIA(), and LoadMapByFile().
{
     CMatrice Matrice;
     Matrice.resize(NbLine);
     for (unsigned i(0); i < NbLine; ++i)
         for (unsigned j(0); j < NbColumn; ++j)
             Matrice[i].push_back(CaseEmpty);
     for (unsigned i(PlayerX.m_Y); i < PlayerX.m_Y + PlayerX.m_sizeY; ++i)
         for (unsigned j(PlayerX.m_X); j < PlayerX.m_X + PlayerX.m_sizeX; ++j)
             Matrice[i][j] = PlayerX.m_token;
     for (unsigned i(PlayerY.m_Y); i < PlayerY.m_Y + PlayerY.m_sizeY; ++i)
         for (unsigned j(PlayerY.m_X); j < PlayerY.m_X + PlayerY.m_sizeX; ++j)
             Matrice[i][j] = PlayerY.m_token;
     if (ShowBorder) {
         for (unsigned i(0); i < NbLine; ++i) {
             Matrice[i][0] = CaseBorder;
             Matrice[i][NbColumn - 1] = CaseBorder;
         }
         for (unsigned i(0); i < NbColumn; ++i) {
             Matrice[0][i] = CaseBorder;
             Matrice[NbLine - 1][i] = CaseBorder;
         }
     }
     return Matrice;
 } //InitMatrice()
SObstacle InitObstacle (const unsigned AxeX, const unsigned AxeY, const char Token)
Initiate values to an empty obstacle.
Parameters
[in] AxeX Position X of obstacle
[in] AxeY Position Y of obstacle
[in] Token obstacle token
Returns
Final obstacle
Definition at line 701 of file main.cpp.
References SObstacle::m_token, SObstacle::m_X, and SObstacle::m_Y.
Referenced by DetectObstacle(), DisplayEditor(), and GenerateStaticObject().
{
     SObstacle Obstacle;
     Obstacle.m_X = AxeX;
     Obstacle.m_Y = AxeY;
     Obstacle.m_token = Token;
     return Obstacle;
 } //InitObstacle()
void InitOptions ()
Initiate defaults options.
Definition at line 301 of file main.cpp.
References BonusX, BonusY, BonusZ, BShowHistory, BShowRules, CaseBorder, CaseEmpty, CaseObstacle, CMouvBot, CMouvLeft, CMouvRight, CMouvTop, KDifficult, KSizeX, KSizeY, TokenPlayerX, TokenPlayerY, VOptionsName, and VOptionValue.
Referenced by main().
                    {
     /*
     All configs go here (InitOptions()) AND in header part (simple declaration) AND in SetConfig()
     All DEFAULT values go here
     */
     KSizeX = 10;
     KSizeY = 10;
     KDifficult = 1;
     BonusX = 'W';
     BonusY = 'V';
     BonusZ = 'U';
     CMouvLeft = 'q';
     CMouvTop = 'z';
     CMouvBot = 's';
     CMouvRight = 'd';
     CaseEmpty = '.';
     CaseObstacle = '#';
     CaseBorder = '#';
     TokenPlayerX = 'X';
     TokenPlayerY = 'O';
     BShowHistory = true;
     BShowRules = true;
     VOptionsName = { "CaseEmpty", "TokenPlayerX", "TokenPlayerY", "KSizeX", "KSizeY",  "KDifficult", "BShowRules", "BShowHistory" };
     VOptionValue = { ".",  "X" ,"O", "10", "10", "1", "true", "true" };
     if (1 == KDifficult) VOptionValue[5] = "1";
     else VOptionValue[5] = "0";
 } //InitOptions()
SPlayer InitPlayer (const unsigned Largeur, const unsigned Hauteur, const unsigned AxeX, const unsigned AxeY, const char Token)
Initiate values to an empty player.
Parameters
[in] Largeur Player's width
[in] Hauteur Player's height
[in] AxeX Position X of player
[in] AxeY Position Y of player
[in] Token player token
Returns
Final player
Definition at line 929 of file main.cpp.
References SPlayer::m_score, SPlayer::m_sizeX, SPlayer::m_sizeY, SPlayer::m_token, SPlayer::m_X, and SPlayer::m_Y.
Referenced by DisplayEditor(), DisplayMulti(), and DisplaySoloIA().
{
     SPlayer Player;
     Player.m_sizeX = Largeur;
     Player.m_sizeY = Hauteur;
     Player.m_X = AxeX;
     Player.m_Y = AxeY;
     Player.m_token = Token;
     /*Constant values below*/
     Player.m_score = 0;
     return Player;
 }//InitPlayer()
bool IsBonusTaken (const SPlayer & Player)
Check if player got the bonus that make his size up.
Parameters
[in] Player Player to check
Returns
Return true if the bonus was taken
Definition at line 915 of file main.cpp.
References SPlayer::m_sizeX.
Referenced by MovePlayer().
{
     return (1 == Player.m_sizeX ? false : true);
 }//IsBonusTaken()
bool IsMovementForbidden (SPlayer & Player, char & Movement)
Check if player can move to the position he decided to go.
Parameters
[in] Player Player to check
[in] Movement The movement that the player will do
Returns
True if player can move to his future movement
Definition at line 764 of file main.cpp.
References CMouvBot, CMouvLeft, CMouvRight, CMouvTop, SPlayer::m_score, SPlayer::m_sizeX, SPlayer::m_X, SPlayer::m_Y, SLog, and VObstacle.
Referenced by MovePlayer().
{
     if (Player.m_sizeX != 1) return false;
     for (unsigned i(0); i < VObstacle.size(); ++i) {
         if (VObstacle[i].m_X == Player.m_X  &&
             VObstacle[i].m_Y == Player.m_Y - 1 && Movement == CMouvTop) {
             SLog += "\n\r\n\r Ce bonus vous a fait PERDRE 8 en score !";
             Player.m_score -= 8;
             return true;
         }
         else if (VObstacle[i].m_X == Player.m_X  &&
             VObstacle[i].m_Y == Player.m_Y + 1 && Movement == CMouvBot) {
             SLog += "\n\r\n\r Ce bonus vous a fait PERDRE 8 en score !";
             Player.m_score -= 8;
             return true;
         }
         else if (VObstacle[i].m_X == Player.m_X - 1 &&
             VObstacle[i].m_Y == Player.m_Y  && Movement == CMouvLeft) {
             SLog += "\n\r\n\r Ce bonus vous a fait PERDRE 8 en score !";
             Player.m_score -= 8;
             return true;
         }
         else if (VObstacle[i].m_X == Player.m_X + 1 &&
             VObstacle[i].m_Y == Player.m_Y  && Movement == CMouvRight) {
             SLog += "\n\r\n\r Ce bonus vous a fait PERDRE 8 en score !";
             Player.m_score -= 8;
             return true;
         }
     }
     return false;
 }//IsMovementForbidden()
bool IsPersoMapRecquiered ()
Ask the player if a public map is wanted.
Returns
True if player want public map
Definition at line 1123 of file main.cpp.
References Color(), KReset(), KRouge(), PrintLines(), and ShowTitle().
Referenced by DisplayMulti(), and DisplaySoloIA().
{
     char Choice;
     string MapName;
     ShowTitle("multi.title");
     PrintLines(1);
 recheck:
     Color(KRouge);
     cout << "\n\r\n\r[?] Voulez-vous charger une map prdfinie ? [y /n /l]";
     cout << "\n\r(Vous pouvez lister vos maps avec la touche L) : ";
     cin >> Choice;
     if ('y' == Choice || 'Y' == Choice) return true;
     else if ('l' == Choice || 'L' == Choice) {
         Color(KReset);
         PrintLines(1);
         system("ls ./Nos_fichiers/map");
         PrintLines(1);
         goto recheck;
     }
     else if ('n' == Choice || 'n' == Choice) return false;
 return false;
 } //isPersoMapRecquiered
bool IsSurrounded (CMatrice & Map, SPlayer & Player)
Check if player is surrounded of obstacles.
Parameters
[in] Matrice The game map
[in] Player The player to check
Returns
True if player is surrounded
Definition at line 688 of file main.cpp.
References CaseObstacle, SPlayer::m_X, and SPlayer::m_Y.
Referenced by GenerateStaticObject().
{
     return (Map[Player.m_X + 1][Player.m_Y + 1] == CaseObstacle);
 }//IsSurrounded()
const string KBleu ("34")
Referenced by DisplayEditor(), DisplayMulti(), DisplaySoloIA(), and ShowMatrice().
const string KBold ("1")
Referenced by ShowMatrice().
const string KCyan ("36")
Referenced by DisplayEditor(), DisplayInfos(), DisplayMenu(), DisplayOption(), and GetTourMax().
void KeyEvent (const int & ch, CMatrice & Map, SPlayer & Player)
Move player to the position depending of what he typed.
Parameters
[in] ch Entered key
[in] Map Game's map
[in] Player Player to move
Definition at line 1021 of file main.cpp.
References CMouvBot, CMouvLeft, CMouvRight, CMouvTop, and MovePlayer().
Referenced by DisplayMulti(), and DisplaySoloIA().
{
     if (ch == CMouvTop)
         MovePlayer(Map, CMouvTop, Player);
     else if (ch == CMouvBot)
         MovePlayer(Map, CMouvBot, Player);
     else if (ch == CMouvLeft)
         MovePlayer(Map, CMouvLeft, Player);
     else if (ch == CMouvRight)
         MovePlayer(Map, CMouvRight, Player);
     else if (ch == char(3)/*CTRL+C*/) {
         cout << endl;
         endwin();
         exit(0);
     }
     else if (ch == 'r'/*RESTART*/) {
         cout << endl;
         endwin();
         system("rm main.out 2>/dev/null; g++ -std=c++11  main.cpp -o main.out -Wall -ltinfo -lncurses; ./main.out");
         exit(0);
     }
 }//KeyEvent()
const string KHBleu ("44")
Referenced by DisplayWin().
const string KHCyan ("46")
Referenced by DisplayMenu(), DisplayWin(), and ShowMatrice().
const string KHGris ("47")
Referenced by DisplayLog(), and DisplayWin().
const string KHJaune ("43")
Referenced by DisplayEditor(), DisplayMenu(), DisplayMulti(), DisplaySoloIA(), DisplayWin(), and ShowMatrice().
const string KHMagenta ("45")
const string KHNoir ("40")
Referenced by ShowMatrice().
const string KHRouge ("41")
const string KHVert ("42")
Referenced by DisplayInfos(), and ShowMatrice().
const string KJaune ("33")
Referenced by DisplayInfos().
const string KMagenta ("35")
Referenced by DisplayMulti(), DisplaySoloIA(), and ShowMatrice().
const string KNoir ("30")
const string KOverLine ("53")
const string KReset ("0")
Referenced by AskForMap(), DisplayEditor(), DisplayInfos(), DisplayLog(), DisplayMenu(), DisplayMulti(), DisplayOption(), DisplaySoloIA(), DisplayWin(), GetTourMax(), IsPersoMapRecquiered(), main(), and ShowMatrice().
const string KRouge ("31")
Referenced by DisplayEditor(), DisplayInfos(), DisplayLog(), DisplayMenu(), DisplayOption(), DisplayWin(), GetTourMax(), IsPersoMapRecquiered(), and ShowMatrice().
const string KUnderLine ("4")
const string KVert ("32")
Referenced by DisplayInfos(), and ShowMatrice().
void ListenKeyboard ()
Listen to keyboard using no-canonical mode.
Definition at line 243 of file main.cpp.
Referenced by DisplayEditor(), DisplayMulti(), and DisplaySoloIA().
                       {
     raw();
     keypad(stdscr, TRUE);
     noecho();
 } //ListenKeyboard()
CMatrice LoadMapByFile (const string & MapName)
Load map by file.
Parameters
[in] MapName The map to load
Returns
Loaded matrix
Bug:
Relancer le programme si le nom entr n'est pas valide
Definition at line 506 of file main.cpp.
References GetMaxColumn(), GetMaxLine(), InitMatrice(), PlayerX, and PlayerY.
Referenced by DisplayMulti(), and DisplaySoloIA().
{
     const string FullName = "./Nos_fichiers/map/MyMap_" + MapName + ".map";
     unsigned NbLine = GetMaxLine(FullName);
     unsigned NbColumn = GetMaxColumn(FullName);
     CMatrice LoadedMatrice = InitMatrice(NbLine, NbColumn, PlayerX, PlayerY);
     vector <string> MapLines;
     string ReadedLine;
     ifstream ifs(FullName);
     while (!ifs.eof()) {
         getline(ifs, ReadedLine);
         if (!(ReadedLine == "\n\r" || ReadedLine[0] == '\n'))
             MapLines.push_back(ReadedLine);
     }
     ifs.clear();
     for (unsigned i(0); i < LoadedMatrice.size(); ++i) {
         for (unsigned a(0); a < LoadedMatrice[i].size(); ++a) {
             LoadedMatrice[i][a] = MapLines[i][a];
         }
     }
     return LoadedMatrice;
 }
int main ()
Definition at line 1611 of file main.cpp.
References Color(), DisplayMenu(), InitOptions(), KReset(), and PrintLines().
            {
     InitOptions();
     DisplayMenu();
     endwin();
     Color(KReset);
     PrintLines(3);
     return 0;
 } //main()
void MoveBot (int & ch, CMatrice & Map, const unsigned & Tour)
Move bot to a specific position.
Parameters
[in] ch Entered key
[in] Map Game map
[in] Tour Actual round
Definition at line 1054 of file main.cpp.
References CMouvBot, CMouvLeft, CMouvRight, CMouvTop, SPlayer::m_X, SPlayer::m_Y, MovePlayer(), PlayerX, and PlayerY.
Referenced by DisplaySoloIA().
{
     if (1 == Tour % 2 && (!(PlayerX.m_X == PlayerY.m_X))) {
         if (PlayerY.m_X - 1 < PlayerX.m_X) MovePlayer(Map, CMouvRight, PlayerY);
         else MovePlayer(Map, CMouvLeft, PlayerY);
     }
     else {
         if (!(PlayerX.m_Y == PlayerY.m_Y)) {
             if ((PlayerY.m_Y - 1) < PlayerX.m_Y) MovePlayer(Map, CMouvBot, PlayerY);
             else MovePlayer(Map, CMouvTop, PlayerY);
         }
     }
 }//MoveBot()
void MovePlayer (CMatrice & Matrice, char Move, SPlayer & Player)
Move player to a specific position.
Parameters
[in] Matrice Game map
[in] Move Player's movement
[in] Player Player to move
Definition at line 951 of file main.cpp.
References CaseEmpty, CMouvBot, CMouvLeft, CMouvRight, CMouvTop, GetBonus(), IsBonusTaken(), IsMovementForbidden(), SPlayer::m_history, SPlayer::m_sizeX, SPlayer::m_sizeY, SPlayer::m_token, SPlayer::m_X, and SPlayer::m_Y.
Referenced by DisplayEditor(), KeyEvent(), and MoveBot().
{
     unsigned Additional(0);
     if (IsMovementForbidden(Player, Move)) return;
     Player.m_history.push_back(toupper(Move));
     if (IsBonusTaken(Player)) Additional = 1;
     if (Move == CMouvTop) {
         if (Player.m_Y + Player.m_sizeY > 2 + Additional)
         {
             --Player.m_Y;
             GetBonus(Matrice, Player);
             for (unsigned i(Player.m_X); i < Player.m_X + Player.m_sizeX; ++i) {
                 Matrice[Player.m_Y + Player.m_sizeY][i] = CaseEmpty;
                 Matrice[Player.m_Y][i] = Player.m_token;
             }
         }
     }
     else if (Move == CMouvBot) {
         if (Player.m_Y + Player.m_sizeY < Matrice.size() - 1) {
             ++Player.m_Y;
             GetBonus(Matrice, Player);
             for (unsigned i(Player.m_X); i < Player.m_X + Player.m_sizeX; ++i) {
                 Matrice[Player.m_Y - 1][i] = CaseEmpty;
                 Matrice[Player.m_Y + Player.m_sizeY - 1][i] = Player.m_token;
             }
         }
     }
     else if (Move == CMouvLeft) {
         if (Player.m_X + Player.m_sizeY > 2 + Additional)
         {
             --Player.m_X;
             GetBonus(Matrice, Player);
             for (unsigned i(Player.m_Y); i < Player.m_Y + Player.m_sizeY; ++i) {
                 Matrice[i][Player.m_X + Player.m_sizeX] = CaseEmpty;
                 Matrice[i][Player.m_X] = Player.m_token;
             }
         }
     }
     else if (Move == CMouvRight) {
         if (Player.m_X + Player.m_sizeX < Matrice[0].size() - 1)
         {
             ++Player.m_X;
             GetBonus(Matrice, Player);
             for (unsigned i(Player.m_Y); i < Player.m_Y + Player.m_sizeY; ++i) {
                 Matrice[i][Player.m_X - 1] = CaseEmpty;
                 Matrice[i][Player.m_X + Player.m_sizeX - 1] = Player.m_token;
             }
         }
     }
 }//MovePlayer()
void PrintLines (const unsigned & LineNumber)
PrintLines.
Parameters
[in] LineNumber Number of line to display
Definition at line 261 of file main.cpp.
Referenced by DisplayEditor(), DisplayMulti(), DisplaySoloIA(), DisplayWin(), IsPersoMapRecquiered(), main(), ShowMatrice(), and ShowTitle().
{
     for (unsigned i(0); i < LineNumber; ++i) cout << endl;
 } //PrintLines
void PutBonus (CMatrice & Matrice, SBonus & Bonus)
Put bonus to matrix.
Parameters
[in] Matrice Matrix where the bonus will be put on
[in] Bonus Bonus to put
Definition at line 629 of file main.cpp.
References KSizeX, KSizeY, SBonus::m_token, SBonus::m_X, and SBonus::m_Y.
Referenced by DisplayEditor(), and GenerateStaticObject().
{
     if ((Bonus.m_Y > 1 && Bonus.m_X > 1) && (Bonus.m_Y < KSizeY - 1 && Bonus.m_X < KSizeX - 1))
         Matrice[Bonus.m_Y][Bonus.m_X] = Bonus.m_token;
 }//PutBonus()
void PutObstacle (CMatrice & Matrice, SObstacle & Obstacle)
Put obstacle to matrix.
Parameters
[in] Matrice Matrix where the obstacle will be put on
[in] Obstacle Obstacle to put
Definition at line 718 of file main.cpp.
References SObstacle::m_token, SObstacle::m_X, SObstacle::m_Y, and VObstacle.
Referenced by DisplayEditor(), and GenerateRandomObstacles().
{
     for (int i = -1; i < 1; ++i) {
         if ((Matrice[Obstacle.m_Y + i][Obstacle.m_X + i] != (int)Matrice.size())) {
             Matrice[Obstacle.m_Y][Obstacle.m_X] = Obstacle.m_token;
             VObstacle.push_back(Obstacle);
         }
     }
 } //PutObstacle()
int Rand (int Min, int Max)
Generate random number.
Parameters
[in] Min Minimum range
[in] Max Maximum range
Returns
Random number between Min and Max
Definition at line 231 of file main.cpp.
Referenced by DisplayMulti(), DisplaySoloIA(), GenerateRandomObstacles(), and GenerateStaticObject().
{
     random_device Random;
     mt19937 Rng(Random());
     uniform_int_distribution<int> uni(Min, Max);
     return uni(Rng);
 }//Rand()
void SetConfig (string Name, const string & Value)
Modify a specific config.
Parameters
[in] Name The configuration name
[in] Value The new value to affect
Definition at line 340 of file main.cpp.
References BShowHistory, BShowRules, CaseEmpty, CMouvBot, CMouvLeft, CMouvRight, CMouvTop, KDifficult, KSizeX, KSizeY, StrToBool(), TokenPlayerX, TokenPlayerY, VOptionsName, and VOptionValue.
Referenced by DisplayOption().
{
     vector<char> Valuetochar(Value.c_str(), Value.c_str() + Value.size() + 1u);
     for (unsigned i(0); i < VOptionsName.size(); ++i)
         if (VOptionsName[i] == Name) VOptionValue[i] = Value;
     if ("CMouvLeft" == Name) CMouvLeft = Valuetochar[0];
     else if ("CMouvTop" == Name) CMouvTop = Valuetochar[0];
     else if ("CMouvBot" == Name) CMouvBot = Valuetochar[0];
     else if ("CMouvRight" == Name) CMouvRight = Valuetochar[0];
     else if ("TokenPlayerX" == Name) TokenPlayerX = Valuetochar[0];
     else if ("CaseEmpty" == Name) CaseEmpty = Valuetochar[0];
     else if ("TokenPlayerY" == Name) TokenPlayerY = Valuetochar[0];
     else if ("KSizeX" == Name) KSizeX = stoul(Value);
     else if ("KSizeY" == Name) KSizeY = stoul(Value);
     else if ("KDifficult" == Name) KDifficult = stoul(Value);
     else if ("BShowRules" == Name) BShowRules = StrToBool(Value);
     else if ("BShowHistory" == Name) BShowHistory = StrToBool(Value);
 } //SetConfig();
void SetTextMiddle ()
Set text to the middle screen.
Definition at line 213 of file main.cpp.
References size.
Referenced by DisplayMulti(), DisplaySoloIA(), and ShowMatrice().
                      {
     cout << setw(round(size.ws_col / 2));
 } //SetTextMiddle()
void ShowMatrice (const CMatrice & Matrice, const bool Clear = true)
Show matrix on console.
Parameters
[in] Matrice The matrix to display
[in] Clear Optional boolean that will clear or not the console
Definition at line 452 of file main.cpp.
References BonusX, BonusY, BonusZ, CaseEmpty, CaseObstacle, ClearScreen(), Color(), KBleu(), KBold(), KHCyan(), KHJaune(), KHNoir(), KHVert(), KMagenta(), KReset(), KRouge(), KVert(), PrintLines(), SetTextMiddle(), TokenPlayerX, and TokenPlayerY.
Referenced by DisplayEditor(), DisplayMulti(), and DisplaySoloIA().
{
     if (Clear) ClearScreen();
     PrintLines(2);
     Color(KReset);
     for (unsigned i(0); i < Matrice.size(); ++i) {
         SetTextMiddle();
         for (unsigned a(0); a < Matrice[i].size(); ++a) {
             /*GESTION DES ColorS*/
             if (Matrice[i][a] == CaseObstacle) {
                 Color(KBold);
                 Color(KHNoir);
             }
             if (Matrice[i][a] == BonusX)
                 Color(KVert, KHVert);
             if (Matrice[i][a] == BonusY)
                 Color(KVert, KHVert);
             if (Matrice[i][a] == BonusZ)
                 Color(KVert, KHVert);
             if (Matrice[i][a] == TokenPlayerX) {
                 Color(KBold);
                 Color(KRouge, KHCyan);
             }
             if (Matrice[i][a] == TokenPlayerY) {
                 Color(KBold);
                 Color(KBleu, KHJaune);
             }
             if (Matrice[i][a] == CaseEmpty)
                 Color(KMagenta);
             cout << Matrice[i][a];
             Color(KReset);
         }
         cout << endl;
     }
 }//ShowMatrice
void ShowTitle (const string & FileName, const bool Clear = true)
Show title from file.
Parameters
[in] FileName File to read in
[in] Clear Clear or not the console (optional)
Definition at line 278 of file main.cpp.
References ClearScreen(), and PrintLines().
Referenced by DisplayEditor(), DisplayMenu(), DisplayMulti(), DisplayOption(), DisplaySoloIA(), and IsPersoMapRecquiered().
{
     ClearScreen();
     string StrTitle;
     string StrDir = "Nos_fichiers/asciititle";
     ifstream IFSTitle(StrDir + '/' + FileName);
     PrintLines(1);
     while (true) {
         if (IFSTitle.eof()) break;
         getline(IFSTitle, StrTitle);
         cout << StrTitle << endl;
     }
     IFSTitle.clear();
 }//ShowTitle()
bool StrToBool (const string & Chaine)
Convert string to bool.
Parameters
[in] Chaine String to convert
Returns
True if Chaine equal to "true"
Definition at line 269 of file main.cpp.
Referenced by SetConfig().
{
     return(Chaine == "true" ? true : false);
 } //StrToBool()
Variable Documentation
char BonusX
Bonus X token.
Definition at line 145 of file main.cpp.
Referenced by DisplayEditor(), DisplayInfos(), GenerateStaticObject(), GetBonus(), InitOptions(), and ShowMatrice().
char BonusY
Bonus Y token.
Definition at line 144 of file main.cpp.
Referenced by DisplayEditor(), DisplayInfos(), GenerateStaticObject(), GetBonus(), InitOptions(), and ShowMatrice().
char BonusZ
Bonus Z token.
Definition at line 146 of file main.cpp.
Referenced by DisplayEditor(), DisplayInfos(), GenerateStaticObject(), GetBonus(), InitOptions(), and ShowMatrice().
bool BShowHistory
Showing history or not.
Definition at line 138 of file main.cpp.
Referenced by DisplayWin(), InitOptions(), and SetConfig().
bool BShowRules
Showing rules or not.
Definition at line 137 of file main.cpp.
Referenced by DisplayInfos(), InitOptions(), and SetConfig().
char CaseBorder
Border case token.
Definition at line 153 of file main.cpp.
Referenced by InitMatrice(), and InitOptions().
char CaseEmpty
Empty case token.
Definition at line 151 of file main.cpp.
Referenced by DisplayEditor(), InitMatrice(), InitOptions(), MovePlayer(), SetConfig(), and ShowMatrice().
char CaseObstacle
Obstacle case token.
Definition at line 152 of file main.cpp.
Referenced by DetectObstacle(), DisplayEditor(), DisplayInfos(), GenerateStaticObject(), InitOptions(), IsSurrounded(), and ShowMatrice().
char CMouvBot
Key associed to bot movement.
Definition at line 149 of file main.cpp.
Referenced by InitOptions(), IsMovementForbidden(), KeyEvent(), MoveBot(), MovePlayer(), and SetConfig().
char CMouvLeft
Key associed to left movement.
Definition at line 147 of file main.cpp.
Referenced by InitOptions(), IsMovementForbidden(), KeyEvent(), MoveBot(), MovePlayer(), and SetConfig().
char CMouvRight
Key associed to rigght movement.
Definition at line 150 of file main.cpp.
Referenced by InitOptions(), IsMovementForbidden(), KeyEvent(), MoveBot(), MovePlayer(), and SetConfig().
char CMouvTop
Key associed to top movement.
Definition at line 148 of file main.cpp.
Referenced by InitOptions(), IsMovementForbidden(), KeyEvent(), MoveBot(), MovePlayer(), and SetConfig().
unsigned KDifficult
Difficulty.
Definition at line 142 of file main.cpp.
Referenced by DisplayInfos(), DisplayMulti(), DisplaySoloIA(), GetBonus(), InitOptions(), and SetConfig().
unsigned KSizeX
Matrix size (X axe)
Definition at line 141 of file main.cpp.
Referenced by DisplayInfos(), DisplayMulti(), DisplaySoloIA(), GenerateStaticObject(), InitOptions(), PutBonus(), and SetConfig().
unsigned KSizeY
Matrix size (Y axe)
Definition at line 140 of file main.cpp.
Referenced by DisplayInfos(), DisplayMulti(), DisplaySoloIA(), GenerateStaticObject(), InitOptions(), PutBonus(), and SetConfig().
SPlayer PlayerX
First player.
Definition at line 157 of file main.cpp.
Referenced by DisplayEditor(), DisplayMulti(), DisplaySoloIA(), DisplayWin(), GenerateStaticObject(), LoadMapByFile(), and MoveBot().
SPlayer PlayerY
First player.
Definition at line 158 of file main.cpp.
Referenced by DisplayEditor(), DisplayMulti(), DisplaySoloIA(), DisplayWin(), GenerateStaticObject(), LoadMapByFile(), and MoveBot().
struct winsize size
Definition at line 129 of file main.cpp.
Referenced by InitCurses(), and SetTextMiddle().
string SLog
log string
Definition at line 134 of file main.cpp.
Referenced by DisplayEditor(), DisplayLog(), DisplayOption(), GetBonus(), and IsMovementForbidden().
char TokenPlayerX
First player token.
Definition at line 154 of file main.cpp.
Referenced by DisplayMulti(), DisplaySoloIA(), InitOptions(), SetConfig(), and ShowMatrice().
char TokenPlayerY
Second player token.
Definition at line 155 of file main.cpp.
Referenced by DisplayMulti(), DisplaySoloIA(), InitOptions(), SetConfig(), and ShowMatrice().
vector<SObstacle> VObstacle
all referenced obstacles
Definition at line 131 of file main.cpp.
Referenced by DetectObstacle(), IsMovementForbidden(), and PutObstacle().
vector<string> VOptionsName
options names
Definition at line 132 of file main.cpp.
Referenced by DisplayOption(), InitOptions(), and SetConfig().
vector<string> VOptionValue
options values
Definition at line 133 of file main.cpp.
Referenced by DisplayOption(), InitOptions(), and SetConfig().